#!/bin/sh

# Displays number of unread news items and an loading icon if updating.
# When clicked, brings up `newsboat`.

btn="${BUTTON:-${BLOCK_BUTTON:-0}}"

case "$btn" in
        1) setsid -f "$TERMINAL" -e newsboat ;;
	2) setsid -f newsup >/dev/null && pkill -RTMIN+6 "${STATUSBAR:-dwmblocks}" && exit ;;
        3) notify-send "📰 News module" "\- Shows unread news items
- Shows 🔃 if updating with \`newsup\`
- Left click opens newsboat
- Middle click syncs RSS feeds
<b>Note:</b> Only one instance of newsboat (including updates) may be running at a time." ;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

 cat /tmp/newsupdate 2>/dev/null || echo "$(newsboat -x print-unread | awk '{ if($1>0) print "📰" $1}')$(cat "${XDG_CONFIG_HOME:-$HOME/.config}"/newsboat/.update 2>/dev/null)"
