#!/bin/sh
case "$(file -Lb --mime-type -- "$1")" in
  text/*) bat --color=always --style=numbers --line-range=:200 "$1" ;;
  image/*) chafa -f symbols -s 80x24 "$1" ;;
  application/pdf) pdftotext "$1" - | head -200 ;;
  application/zip|application/*tar*|application/*compress*) atool -l "$1" ;;
  *) file -Lb -- "$1" ;;
esac
